### ISSUE TITLE
[BUG] !settag overwrites the old tag if using the same tag name

### ISSUE THREAD

**Issue by JavaCafe01** [unixporn/robbb#74] opened 2021-04-06 02:45 UTC
## Expected behaviour
Robbb should not automatically overwrite, and should either reply saying the tag exists or give more options (What should we do?)

## Current behaviour
Overwrites like a chad

If this is still a problem I will assign this to myself to work on

**Comment by elkowar** [comment] 2021-04-18 09:12
I guess giving an error message and explicitly forcing to deletetag first would make sense
although I'd say it could be cool if we made it only do that if the tag has not been written by the same user
as in:
I write tag
i override tag: just works

you write tag
i override tag: error

**Comment by 6gk** [comment] 2021-12-12 11:15
not a bug

**Comment by 6gk** [comment] 2021-12-12 11:15
works well

**Comment by elkowar** [comment] 2022-05-19 08:03
Settag now has a fancy modal UI that actually shows the old value, thus making it very obvious that you're overriding.
Closing this

**Closed by elkowar** 2022-05-19 08:03 UTC
Labels: bug, not a bug
