### ISSUE TITLE
[BUG] !notes doesn't show context link for mute/warns

### ISSUE THREAD

**Issue by 6gk** [unixporn/robbb#135] opened 2021-06-11 11:18 UTC
## Expected behaviour
Works

## Current behaviour
Doesn't work :/

**Comment by elkowar** [comment] 2021-07-11 17:36
duplicate of #106 lol

**Closed by elkowar** 2021-07-11 17:36 UTC
Labels: bug

**Comment by 6gk** [comment] 2021-07-11 17:39
imagine checking issues first lol
also imagine remembering the issues you made lol
